CREATE TABLE TB_RESPONSAVEL (
    ID_RESPONSAVEL NUMBER PRIMARY KEY,

    NM_RESPONSAVEL VARCHAR2(100) NOT NULL,

    NR_DOCUMENTO VARCHAR2(20) UNIQUE,

    NR_TELEFONE VARCHAR2(20),

    DS_EMAIL VARCHAR2(100),

    DS_ENDERECO VARCHAR2(200),

    DS_PREFERENCIA_CONTATO VARCHAR2(30),

    ST_RECEBE_NOTIFICACAO CHAR(1)
        CHECK (ST_RECEBE_NOTIFICACAO IN ('S', 'N')),

    DT_CADASTRO DATE DEFAULT SYSDATE
);

CREATE TABLE TB_PET (
    ID_PET NUMBER PRIMARY KEY,

    NM_PET VARCHAR2(80) NOT NULL,

    DS_ESPECIE VARCHAR2(50) NOT NULL,

    DS_RACA VARCHAR2(80),

    DT_NASCIMENTO DATE,

    NR_PESO NUMBER(5,2),

    NR_ALTURA NUMBER(5,2),

    DS_SEXO CHAR(1)
        CHECK (DS_SEXO IN ('M', 'F')),

    DS_ALERGIAS VARCHAR2(300),

    ST_CASTRADO CHAR(1)
        CHECK (ST_CASTRADO IN ('S', 'N')),

    DS_COR_PELAGEM VARCHAR2(50),

    DS_MICROCHIP VARCHAR2(50) UNIQUE,

    DT_CADASTRO DATE DEFAULT SYSDATE,

    ID_RESPONSAVEL NUMBER NOT NULL,

    CONSTRAINT FK_PET_RESPONSAVEL
        FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES TB_RESPONSAVEL(ID_RESPONSAVEL)
);

CREATE TABLE TB_VETERINARIO (
    ID_VETERINARIO NUMBER PRIMARY KEY,

    NM_VETERINARIO VARCHAR2(100) NOT NULL,

    NR_CRMV VARCHAR2(20) UNIQUE NOT NULL,

    DS_ESPECIALIDADE VARCHAR2(80),

    DS_TIPO_ATUACAO VARCHAR2(20) NOT NULL,

    DS_EMAIL VARCHAR2(150) UNIQUE,

    NR_TELEFONE VARCHAR2(15),

    DS_STATUS VARCHAR2(20),

    DT_CADASTRO DATE DEFAULT SYSDATE
);

CREATE TABLE TB_CLINICA (
    ID_CLINICA NUMBER PRIMARY KEY,

    NM_CLINICA VARCHAR2(100) NOT NULL,

    NR_CNPJ VARCHAR2(14) UNIQUE,

    DS_EMAIL VARCHAR2(150) UNIQUE,

    NR_TELEFONE VARCHAR2(15),

    DS_LOGRADOURO VARCHAR2(100),

    NR_ENDERECO VARCHAR2(10),

    DS_BAIRRO VARCHAR2(60),

    DS_CIDADE VARCHAR2(60),

    DS_ESTADO VARCHAR2(2),

    NR_CEP VARCHAR2(8),

    DS_TIPO_ESTABELECIMENTO VARCHAR2(40),

    DS_ESPECIALIDADE_PRINCIPAL VARCHAR2(80),

    ST_ATENDIMENTO_24H CHAR(1)
        CHECK (ST_ATENDIMENTO_24H IN ('S', 'N')),

    ST_ATENDE_EMERGENCIA CHAR(1)
        CHECK (ST_ATENDE_EMERGENCIA IN ('S', 'N')),

    DS_STATUS VARCHAR2(20),

    DT_CADASTRO DATE DEFAULT SYSDATE
);

CREATE TABLE TB_VINCULO_CLINICA_VET (
    ID_VINCULO_CLINICA_VET NUMBER PRIMARY KEY,

    ID_VETERINARIO NUMBER NOT NULL,

    ID_CLINICA NUMBER NOT NULL,

    DT_INICIO_VINCULO DATE,

    DT_FIM_VINCULO DATE,

    DS_TIPO_VINCULO VARCHAR2(30),

    DS_STATUS VARCHAR2(20),

    CONSTRAINT FK_VINCULO_VETERINARIO
        FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_VETERINARIO(ID_VETERINARIO),

    CONSTRAINT FK_VINCULO_CLINICA
        FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_CLINICA(ID_CLINICA)
);

CREATE TABLE TB_CONSULTA (
    ID_CONSULTA NUMBER PRIMARY KEY,

    ID_PET NUMBER NOT NULL,

    ID_VETERINARIO NUMBER NOT NULL,

    ID_CLINICA NUMBER,

    DT_CONSULTA DATE NOT NULL,

    DS_TIPO_CONSULTA VARCHAR2(40) NOT NULL,

    DS_SINTOMAS VARCHAR2(500),

    DS_DIAGNOSTICO VARCHAR2(500),

    DS_OBSERVACOES VARCHAR2(500),

    DT_RETORNO_PREVISTO DATE,

    DS_STATUS VARCHAR2(20),

    CONSTRAINT FK_CONSULTA_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PET(ID_PET),

    CONSTRAINT FK_CONSULTA_VETERINARIO
        FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_VETERINARIO(ID_VETERINARIO),

    CONSTRAINT FK_CONSULTA_CLINICA
        FOREIGN KEY (ID_CLINICA)
        REFERENCES TB_CLINICA(ID_CLINICA)
);

CREATE TABLE TB_TRATAMENTO (
    ID_TRATAMENTO NUMBER PRIMARY KEY,

    ID_PET NUMBER NOT NULL,

    ID_CONSULTA NUMBER NOT NULL,

    ID_VETERINARIO NUMBER NOT NULL,

    DS_MEDICAMENTO VARCHAR2(100),

    DS_DOSAGEM VARCHAR2(50),

    DS_FREQUENCIA VARCHAR2(50),

    DT_INICIO DATE NOT NULL,

    DT_FIM DATE,

    DS_ORIENTACOES VARCHAR2(500),

    DS_STATUS VARCHAR2(20),

    NR_ADESAO NUMBER(5,2),

    DS_EVOLUCAO VARCHAR2(500),

    CONSTRAINT FK_TRATAMENTO_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PET(ID_PET),

    CONSTRAINT FK_TRATAMENTO_CONSULTA
        FOREIGN KEY (ID_CONSULTA)
        REFERENCES TB_CONSULTA(ID_CONSULTA),

    CONSTRAINT FK_TRATAMENTO_VETERINARIO
        FOREIGN KEY (ID_VETERINARIO)
        REFERENCES TB_VETERINARIO(ID_VETERINARIO)
);

CREATE TABLE TB_ALERTA (
    ID_ALERTA NUMBER PRIMARY KEY,

    ID_PET NUMBER NOT NULL,

    ID_CONSULTA NUMBER,

    ID_TRATAMENTO NUMBER,

    DT_ALERTA DATE NOT NULL,

    DS_TIPO_ALERTA VARCHAR2(50) NOT NULL,

    DS_NIVEL_RISCO VARCHAR2(20),

    DS_DESCRICAO VARCHAR2(500),

    DS_STATUS VARCHAR2(20),

    ST_NOTIFICADO CHAR(1)
        CHECK (ST_NOTIFICADO IN ('S', 'N')),

    CONSTRAINT FK_ALERTA_PET
        FOREIGN KEY (ID_PET)
        REFERENCES TB_PET(ID_PET),

    CONSTRAINT FK_ALERTA_CONSULTA
        FOREIGN KEY (ID_CONSULTA)
        REFERENCES TB_CONSULTA(ID_CONSULTA),

    CONSTRAINT FK_ALERTA_TRATAMENTO
        FOREIGN KEY (ID_TRATAMENTO)
        REFERENCES TB_TRATAMENTO(ID_TRATAMENTO)
);