-- 1. LISTAR PETS COM SEUS RESPONSÁVEIS
SELECT 
    P.ID_PET,
    P.NM_PET,
    P.DS_ESPECIE,
    P.DS_RACA,
    R.NM_RESPONSAVEL,
    R.NR_TELEFONE
FROM TB_PET P
JOIN TB_RESPONSAVEL R
    ON P.ID_RESPONSAVEL = R.ID_RESPONSAVEL
ORDER BY P.NM_PET;


-- 2. LISTAR CONSULTAS COM PET, VETERINÁRIO E CLÍNICA
SELECT
    C.ID_CONSULTA,
    P.NM_PET,
    V.NM_VETERINARIO,
    CL.NM_CLINICA,
    C.DT_CONSULTA,
    C.DS_TIPO_CONSULTA,
    C.DS_DIAGNOSTICO
FROM TB_CONSULTA C
JOIN TB_PET P
    ON C.ID_PET = P.ID_PET
JOIN TB_VETERINARIO V
    ON C.ID_VETERINARIO = V.ID_VETERINARIO
LEFT JOIN TB_CLINICA CL
    ON C.ID_CLINICA = CL.ID_CLINICA
ORDER BY C.DT_CONSULTA DESC;


-- 3. QUANTIDADE DE CONSULTAS POR VETERINÁRIO
SELECT
    V.NM_VETERINARIO,
    COUNT(C.ID_CONSULTA) AS TOTAL_CONSULTAS
FROM TB_VETERINARIO V
LEFT JOIN TB_CONSULTA C
    ON V.ID_VETERINARIO = C.ID_VETERINARIO
GROUP BY V.NM_VETERINARIO
ORDER BY TOTAL_CONSULTAS DESC;


-- 4. TRATAMENTOS ATIVOS POR PET
SELECT
    P.NM_PET,
    T.DS_MEDICAMENTO,
    T.DS_DOSAGEM,
    T.DS_FREQUENCIA,
    T.DT_INICIO,
    T.DT_FIM,
    T.DS_STATUS
FROM TB_TRATAMENTO T
JOIN TB_PET P
    ON T.ID_PET = P.ID_PET
WHERE T.DS_STATUS = 'ATIVO'
ORDER BY T.DT_INICIO DESC;


-- 5. ALERTAS ATIVOS COM NÍVEL DE RISCO
SELECT
    A.ID_ALERTA,
    P.NM_PET,
    A.DS_TIPO_ALERTA,
    A.DS_NIVEL_RISCO,
    A.DS_DESCRICAO,
    A.DT_ALERTA,
    A.ST_NOTIFICADO
FROM TB_ALERTA A
JOIN TB_PET P
    ON A.ID_PET = P.ID_PET
WHERE A.DS_STATUS = 'ATIVO'
ORDER BY A.DS_NIVEL_RISCO, A.DT_ALERTA DESC;


-- 6. QUANTIDADE DE ALERTAS POR PET
SELECT
    P.NM_PET,
    COUNT(A.ID_ALERTA) AS TOTAL_ALERTAS
FROM TB_PET P
LEFT JOIN TB_ALERTA A
    ON P.ID_PET = A.ID_PET
GROUP BY P.NM_PET
ORDER BY TOTAL_ALERTAS DESC;


-- 7. CLÍNICAS COM SEUS VETERINÁRIOS VINCULADOS
SELECT
    CL.NM_CLINICA,
    V.NM_VETERINARIO,
    VC.DS_TIPO_VINCULO,
    VC.DS_STATUS
FROM TB_VINCULO_CLINICA_VET VC
JOIN TB_CLINICA CL
    ON VC.ID_CLINICA = CL.ID_CLINICA
JOIN TB_VETERINARIO V
    ON VC.ID_VETERINARIO = V.ID_VETERINARIO
ORDER BY CL.NM_CLINICA, V.NM_VETERINARIO;


-- 8. MÉDIA DE ADESÃO DOS TRATAMENTOS POR PET
SELECT
    P.NM_PET,
    ROUND(AVG(T.NR_ADESAO), 2) AS MEDIA_ADESAO
FROM TB_PET P
JOIN TB_TRATAMENTO T
    ON P.ID_PET = T.ID_PET
GROUP BY P.NM_PET
ORDER BY MEDIA_ADESAO ASC;